"""add sold column to waste_items

Revision ID: 3a7f1cc94271
Revises: 3cd9d9f8858e
Create Date: 2025-07-12 11:53:31.238460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7f1cc94271'
down_revision: Union[str, None] = '3cd9d9f8858e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_items', sa.Column('sold', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waste_items', 'sold')
    # ### end Alembic commands ###
