"""add amount_kg to waste_items

Revision ID: 52f3fe8eafb4
Revises: 65d8d847d0ce
Create Date: 2025-07-12 10:21:19.791132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f3fe8eafb4'
down_revision: Union[str, None] = '65d8d847d0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_items', sa.Column('amount_kg', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waste_items', 'amount_kg')
    # ### end Alembic commands ###
