"""Add ai_confidence to waste_items

Revision ID: 57785e7b78ad
Revises: c118fa3c15f8
Create Date: 2025-07-11 17:48:12.257636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57785e7b78ad'
down_revision: Union[str, None] = 'c118fa3c15f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_items', sa.Column('ai_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waste_items', 'ai_confidence')
    # ### end Alembic commands ###
