"""add_sold_at_column_to_waste_items

Revision ID: 8c79a76ad363
Revises: 3a7f1cc94271
Create Date: 2025-07-12 11:58:50.585019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c79a76ad363'
down_revision: Union[str, None] = '3a7f1cc94271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_items', sa.Column('sold_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waste_items', 'sold_at')
    # ### end Alembic commands ###
