"""Add verified and predicted_category to waste_items

Revision ID: c118fa3c15f8
Revises: 
Create Date: 2025-07-11 17:27:12.931093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c118fa3c15f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_items', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('waste_items', sa.Column('predicted_category', sa.String(), nullable=True))
    op.drop_column('waste_items', 'ai_confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waste_items', sa.Column('ai_confidence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('waste_items', 'predicted_category')
    op.drop_column('waste_items', 'verified')
    # ### end Alembic commands ###
