"""change amount_kg to float and set existing to 1.0

Revision ID: d4eff6f41e8b
Revises: 52f3fe8eafb4
Create Date: 2025-07-12 10:23:48.635375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4eff6f41e8b'
down_revision: Union[str, None] = '52f3fe8eafb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waste_items', 'amount_kg',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.execute("UPDATE waste_items SET amount_kg = 1.0 WHERE amount_kg IS NULL OR amount_kg != 1.0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('waste_items', 'amount_kg',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
